### PR TITLE
Update binding for electron 4.x

### PR DESCRIPTION
**Pull request by trodi**
Attempting to address #32 

According to the documentation already linked in the above issue, this change appears to be the fix. However, I'm unsure of the steps to build `electron-edge-js` so I haven't tested. I'm happy to build and test, if you can point me to build steps. Thanks.

### CODE REVIEW

**Comment by agracio** [comment]
`tools`build.bat release 10.11.0`

**Comment by buettner123** [comment]
Just tried it out on my side and it still fails.

What I did:
- `npm i`
- `tools\build.bat release 10.11.0` (went through well)
- copied over the lib folder to my projects node_modules electron-edge-js folder
- tried to start the app

=> Error from linked issue persists: 
```
App threw an error during load
Error: The specified procedure could not be found.
\\?\...\noah_electron\noahApp\dist\node_modules\electron-edge-js\lib\native\win32\x64\10.11.0\edge_nativeclr.node
```

**Comment by allisonshaw** [comment]
With the updates from #32 I was able to rebuild and everything works now.

This pull request is ready to merge, @agracio . Then a new version of electron-edge-js can be released that will support Electron 4.0.0.

**Comment by stereokai** [comment]
@allisonshaw which updates in particular?

**Comment by Hammster** [comment]
@stereokai it is up to @agracio now, and since the pull is still open, there are no updates yet.

**Comment by stereokai** [comment]
@Hammster: @allisonshaw wrote "*With the updates from #32 I was able to rebuild* and everything works now."

I'm trying to get this PR to work on my machine, but I'm getting a `node_modules\electron-edge-js\lib\native\win32\x64\10.11.0\edge_nativeclr` error. (I installed directly from the latest commit in the PR).

That's why I asked :)

**Comment by agracio** [comment]
Tried rebuilding using this PR changes but so far it made no difference. Are there any more changes that are missing?

**Comment by absalonv** [comment]
@allisonshaw were you running the 4.0.0 exactly? or newer?

**Comment by stereokai** [comment]
@agracio The pre-compiled binaries in this PR are working for me with Electron 4.0.3. From v4.0.4 they will not work, and will need recompilation on the user machine (see reason in my previous comment). You can try this for yourself by using `npm i git://github.com/agracio/electron-edge-js.git#bb83c09ea7b01426055878fa651cdd57b9388479`

**Comment by agracio** [comment]
I would prefer to have a concrete build process that does not rely on 'hacked' pre-compiled binaries. I will merge binaries if they are updated to 4.0.4 and will mark in README that only 4.0.4 and above are supported. But I would only do it as a one off, and would need a concrete build process steps going forward.

**Comment by stereokai** [comment]
These PR compiles fine in repos using Electron 4.0.0-4.0.3.

For 4.0.4+ [there is a workaround](https://github.com/electron-userland/electron-builder/issues/3660#issuecomment-465461491) until Electron devs fix `electron-builder`

**Comment by agracio** [comment]
I have used the following approach: use new `byndings.gyp` and `build.bat` from this PR, build using `build.bat release 10.11.0`. Then used produces binaries in https://github.com/agracio/electron-edge-js-quick-start on Electron 4.0.0. Results are exactly the same `Error: The specified procedure could not be found.`
I understand that if I used the binaries it would have worked, but I am talking about a standalone build process.

**Comment by allisonshaw** [comment]
@stereokai updates from [this comment] (https://github.com/agracio/electron-edge-js/issues/32#issuecomment-464369093)
File win_delay_load_hook.cc needs a ```#pragma unmanaged```
I made this change locally which enabled these pre-compiled binaries to be generated.
I need to go make a pull-request with this change on the node-gyp repo so building electron-edge-js doesn't require this additional step. For the moment, anyone can rebuild the binaries after adding the required pragma to.

The pre-compiled binaries on this branch were targeting 4.0.0. In 4.0.4 the version of node must have been updated (yet again) so the binaries will need to be re-compiled I;m assuming.

@agracio I will rebuild the binaries for 4.0.4 and make the change in README as requested. A future version of node-gyp will have the pragma added and the extra step won't be necessary - build process should remain as it is now.

**Comment by agracio** [comment]
@allisonshaw No need to change README, I meant I will do it myself, just add 4.0.4 binaries. Also make sure that changes in `build.bat` and `binding.gyp` are correct in this PR. Reading https://github.com/agracio/electron-edge-js/issues/32#issuecomment-464369093 it appears that this https://github.com/agracio/electron-edge-js/pull/34/files#diff-21e418851ae48f9b11907837add9e39aR22 is not needed?

**Comment by allisonshaw** [comment]
The changes to bindings.gyp should still be required, but I will confirm before adding the new built binaries.
I'll add the binaries tomorrow when I can rebuild and test.

**Comment by stereokai** [comment]
Awesome 😁

**Comment by allisonshaw** [comment]
All changes are complete. Ready for merge, @agracio .

**Comment by agracio** [comment]
Merged and published to npm.

**Pull request merged**
