### PR TITLE
adding electron 7.1

### PR DESCRIPTION
**Pull request by gdavidkov**

### CODE REVIEW

**Comment by Hammster** [comment]
This should not be necessary since electron 6 and 7 share the same ABI (NODE_MODULE_VERSION)

**Comment by gdavidkov** [comment]
Hi,
Yes, you are right, I didn't pay attention. I've updated the PR.

**Comment by Hammster** [comment]
Oh it indeed has, our tooling builds electron-edge manually by taking the version from the package so i did not notice it right away. At least i can say that electron edge works without any complications when build like you did with your PR.

**Comment by agracio** [comment]
@gdavidkov have you tested native .NET modules that you included in this commit? One of the caveats of the earlier rebuilds was a problem with node-gyp, the modules will only work if you use the very latest node-gyp version.

**Comment by gdavidkov** [comment]
@agracio Yes, I have tested with native .NET modules. Our application uses .NET Framework intensively. I use node-gyp@6.0.1.

**Pull request merged**
