### PR TITLE
electron 13

### PR DESCRIPTION
**Pull request by camhart**
electron 13

### CODE REVIEW

**Comment by camhart** [comment]
@agracio any chance we could get this merged and an update released?

**Comment by gdavidkov** [comment]
Hi, I've installed from your branch but I got the following error
(node:14756) UnhandledPromiseRejectionWarning: Error: Module did not self-register: '\\?\C:\\app\node_modules\electron-edge-js\build\Release\edge_nativeclr.node'.
From package.json -   "electron-edge-js": "git+https://github.com/camhart/electron-edge-js.git#master"

**Comment by camhart** [comment]
@gdavidkov thanks for bringing this to my attention.  I'll take a look at fixing it in the next few days.

**Comment by camhart** [comment]
Okay, something within this lib needs updated for electron 13.  I just quickly tried it and it crashed electron.  I'll need some more time to dig into what needs changed and what can be left.

**Comment by camhart** [comment]
Since electron 13 uses the same version of node, I don't believe anything needs changed with this lib.  Closing PR.

**Pull request closed without merging**
